-- ─────────────────────────────────────────────────────────────────────────────
-- 001 — NEUTRALIZADA A PROPÓSITO. No borrar el archivo: rompe la numeración.
-- ─────────────────────────────────────────────────────────────────────────────
--
-- Este archivo creaba `users`, `conversations`, `messages`, `claims` y
-- `knowledge_base`. Las cinco están DROPEADAS: se auditó el código y ninguna se
-- leía ni se escribía desde ningún lado.
--
-- El problema era que `init_db()` corría todas las migraciones en CADA arranque.
-- Como los CREATE eran `IF NOT EXISTS`, no fallaban: simplemente volvían a crear
-- las tablas borradas en el siguiente deploy, en silencio. Se dropeaban a mano y
-- reaparecían solas.
--
-- Se arregló por los dos lados:
--   1. acá, vaciando la migración
--   2. en plataforma/db/, que ahora lleva registro de qué migración ya corrió
--      en vez de reejecutarlas todas
--
-- Lo que reemplazó a `knowledge_base`: la tabla `conocimiento_*` de 004, con
-- HNSW en vez de ivfflat y separada por multiagente.

-- pgvector lo sigue necesitando 004.
CREATE EXTENSION IF NOT EXISTS vector;
